# Generated by Django 3.0.2 on 2020-01-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.CharField(max_length=100)),
                ('extension_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Extension')),
            ],
        ),
    ]
