# Generated by Django 3.0.2 on 2020-01-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configentry',
            old_name='extension_name',
            new_name='extension',
        ),
    ]
