# Generated by Django 3.0.2 on 2020-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200122_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='icon_name',
            field=models.CharField(default='nonpic.ppm', max_length=100),
        ),
    ]
