# Generated by Django 3.0.2 on 2020-01-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_extension_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Extension')),
            ],
        ),
    ]
