# Generated by Django 3.0.2 on 2020-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_saveddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='icon_name',
            field=models.CharField(default='nonpic.png', max_length=100),
        ),
    ]
