from .Extension import Extension
from .PaintExtension import PaintExtension
from .WuerfelnExtension import WuerfelnExtension
from .RainbowExtension import RainbowExtension
from .RaindropsExtension import RaindropsExtension
from .SingleColorExtension import SingleColorExtension
from .SettingsExtension import SettingsExtension
from .GameOfLifeExtension import GameOfLifeExtension
from .ScreenSaverExtension import ScreenSaverExtension